server:
  port: 8081

spring:
  application:
    name: supermarket-action-service
  datasource:
    mssql:
      url: jdbc:sqlserver://10.0.0.132:49170;databaseName=supermarket_db;encrypt=true;trustServerCertificate=true;
      username: supermarket
      password: supermarket
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    postgresql:
      url: jdbc:postgresql://10.0.0.132:5432/supermarket_db
      username: supermarket
      password: supermarket
      driver-class-name: org.postgresql.Driver