server:
  port: 8081

spring:
  application:
    name: supermarket-action-service
  datasource:
    mssql:
      url: jdbc:sqlserver://10.0.0.43:49170;databaseName=supermarket_db;encrypt=true;trustServerCertificate=true;
      username: supermarket
      password: supermarket
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    postgresql:
      url: jdbc:postgresql://10.0.0.43:5432/supermarket_db
      username: supermarket
      password: supermarket
      driver-class-name: org.postgresql.Driver

executors:
  default:
    docker:
      - image: maven:3.8.4-openjdk-11
        auth:
          username: my-docker-username
          password: my-docker-password

jobs:
  sonar_scan:
    docker:
      - image: maven:3.8.4-openjdk-11
    steps:
      - checkout
      - run:
          name: Set up SonarQube analysis
          command: |
            mvn clean verify sonar:sonar \
            -Dsonar.projectKey=supermarket-action-service \
            -Dsonar.projectName=supermarket-action-service \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.token=%SONAR_TOKEN% \
            -Dsonar.maven.plugin.version=3.9.0.215

workflows:
  version: 2
  sonar_workflow:
    jobs:
      - sonar_scan
